#!/bin/bash
set -euo pipefail

###############################################################################
# AI Stack Full Deployment Script
# 3 CPU / 12GB RAM Optimized
# Automated - requires NO manual commands after execution
###############################################################################

# ============================================================================
# Configuration
# ============================================================================
SERVER_DIR="$(cd "$(dirname "$0")" && pwd)"
MODEL_NAME="qwen3-8b"
FAST_MODEL="codellama:7b"
CONCURRENT_AGENTS=2

# Colors for output
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
NC='\033[0m' # No Color

log_info() {
    echo -e "${GREEN}[INFO]${NC} $1"
}

log_warn() {
    echo -e "${YELLOW}[WARN]${NC} $1"
}

log_error() {
    echo -e "${RED}[ERROR]${NC} $1"
}

# ============================================================================
# Step 1: Resource Verification
# ============================================================================
verify_resources() {
    log_info "Verifying server resources..."

    # CPU check
    CPU_COUNT=$(nproc)
    log_info "CPU cores detected: $CPU_COUNT"

    if [ "$CPU_COUNT" -lt 3 ]; then
        log_error "Need at least 3 CPU cores, found $CPU_COUNT"
        exit 1
    fi
    log_info "✅ CPU requirement met (3+ cores)"

    # Memory check
    TOTAL_MEM_GB=$(free -g | grep Mem: | awk '{print $2}')
    if [ -z "$TOTAL_MEM_GB" ]; then
        TOTAL_MEM_GB=$(free -m | grep Mem: | awk '{print $2}')
        TOTAL_MEM_GB=$((TOTAL_MEM_GB / 1024))
    fi
    log_info "Total RAM: ${TOTAL_MEM_GB}GB"

    if [ "$TOTAL_MEM_GB" -lt 12 ]; then
        log_error "Need at least 12GB RAM, found ${TOTAL_MEM_GB}GB"
        exit 1
    fi
    log_info "✅ RAM requirement met (12GB+)"

    # Docker check (optional but recommended)
    if command -v docker &>/dev/null; then
        log_info "✅ Docker found"
        DOCKER_AVAILABLE=true
    else
        log_warn "Docker not found - running without container isolation"
        DOCKER_AVAILABLE=false
    fi
}

# ============================================================================
# Step 3: Environment Configuration
# ============================================================================
configure_environment() {
    log_info "Configuring environment variables..."

    local ENV_FILE="$SERVER_DIR/.env"

    # Check if .env already has values
    if [ -f "$ENV_FILE" ] && grep -q "RUNNER_CPU_SECONDS" "$ENV_FILE" 2>/dev/null; then
        log_info "✅ .env file already configured"
        return 0
    fi

    log_info "Creating .env with 3c/12GB optimized settings..."

    cat > "$ENV_FILE" <<EOF
# AI Stack Deployment - 3 Core / 12GB RAM Optimized
# Generated by start-server.sh on $(date -u +%Y-%m-%d_%H:%M:%S UTC)

# === CORE RESOURCES ===
RUNNER_CPU_SECONDS=60
RUNNER_MEMORY_MB=2048
RUNNER_MAX_OPEN_FILES=256
MAX_AGENT_STEPS=60
MAX_PARALLEL_TOOL_CALLS=4
EXPERT_DISPATCH_ENABLED=True
CONTEXT_TOKEN_LIMIT=32768
CONTEXT_COMPACT_EVERY_STEPS=6
CONTEXT_COMPACT_KEEP_RECENT=4
CONTEXT_COMPACT_THRESHOLD_TOKENS=24000

# Runtime controls (feasible with 12GB)
WEB_SEARCH_ENABLED=True
RUNNER_ENABLE_NETNS=True
ALLOWED_COMMANDS="git,ls,cat,pytest,python,python3,npm,node,make,grep,find,mypy,ruff,black,flake8"

# === MODEL CONFIGURATION ===
DEFAULT_MODEL="$MODEL_NAME"
AGENT_MODEL_ID="orchestrator"
FAST_MODEL="$FAST_MODEL"
ROUTER_MODEL="$MODEL_NAME"
FINANCE_MODEL="$MODEL_NAME"
AGENT_MODEL_ESCALATIONS=2
CHANGE_REVIEW_MODEL_ENABLED=True

# Tier 3 multi-expert dispatch (now feasible with 3 cores)
EXPERT_DISPATCH_ENABLED=True
EXPERT_DISPATCH_MODEL="$MODEL_NAME"
MAX_PARALLEL_EXPERTS=2
EXPERT_MAX_COMPLETION_TOKENS=1024
EXPERT_DISPATCH_TIMEOUT_SECONDS=600

# === NETWORK / SANDBOX ===
# With 3 cores, Docker isolation is feasible
RUNNER_DOCKER_IMAGE="python:3.12-slim"
SANDBOX_ALLOW_EGRESS="git,api,registry"
SANDBOX_DENY_EGRESS=""

# === SERVER ===
AGENT_API_KEY="$(openssl rand -hex 32)"
ALLOW_INSECURE_NO_AUTH=False

# === SERVICE DISCOVERY ===
POSTGRES_URL="postgresql://postgres:postgres@localhost:5432/postgres"
REDIS_URL="redis://localhost:6379/0"
SANDBOX_ROOT="/tmp/agent-sandboxes"
ARTIFACT_ROOT="/tmp/jarvis-artifacts"
EOF

    log_info "✅ .env file created with optimized settings"
}

# ============================================================================
# Step 4: Infrastructure Services Startup
# ============================================================================
start_infrastructure() {
    log_info "Starting infrastructure services (PostgreSQL, Redis, Qdrant)..."

    cd "$SERVER_DIR"

    # Check if docker compose is available
    if [ "$DOCKER_AVAILABLE" = true ]; then
        log_info "Starting services via Docker Compose..."

        # Start core services
        docker compose up -d postgres redis qdrant 2>&1 | tail -5

        # Wait for PostgreSQL to be ready
        log_info "Waiting for PostgreSQL to be ready..."
        for i in $(seq 1 30); do
            if docker exec "$(docker compose ps -q postgres)" pg_isready -U postgres 2>/dev/null; then
                break
            fi
            sleep 1
        done

        # Wait for Redis
        log_info "Waiting for Redis to be ready..."
        for i in $(seq 1 30); do
            if docker exec "$(docker compose ps -q redis)" redis-cli ping 2>/dev/null; then
                break
            fi
            sleep 1
        done

        log_info "✅ Infrastructure services started"
    else
        log_info "Starting services locally (no Docker)..."
        # Try to start services if they're installed natively
        if command -v pg_ctl &>/dev/null; then
            log_info "Starting PostgreSQL locally..."
            pg_ctlcluster 15 main start 2>/dev/null || true
        fi
        if command -v redis-server &>/dev/null; then
            log_info "Starting Redis locally..."
            redis-server --daemonize yes 2>/dev/null || true
        fi
    fi
}

# ============================================================================
# Step 4: AI Stack Server Startup
# ============================================================================
start_server() {
    log_info "Starting AI Stack Server..."

    cd "$SERVER_DIR"

    # Verify the .env is sourced
    if [ -f .env ]; then
        export $(cat .env | grep -v '^#' | grep -v '^$' | xargs)
        log_info "✅ Environment variables loaded"
    else
        log_error ".env file not found"
        exit 1
    fi

    # Check if Ollama is running
    if ! curl -s http://localhost:11434/api/tags >/dev/null 2>&1; then
        log_info "Starting Ollama server..."
        ollama serve &
        sleep 3
    fi

    # Verify models are available
    local MODEL_CHECK=$(ollama list 2>/dev/null | grep "$MODEL_NAME" | wc -l)
    if [ "$MODEL_CHECK" -eq 0 ]; then
        log_info "Pulling model (one-time operation)..."
        ollama pull "$MODEL_NAME" >/dev/null 2>&1
    fi
    log_info "✅ Model verified: $MODEL_NAME"

    # Start the AI Stack server
    log_info "Starting uvicorn server on 0.0.0.0:8000..."
    log_info "Server will be available at: http://$(hostname -I | awk '{print $1}'):8000"

    # Start uvicorn in background
    python3 -m uvicorn app.main:app --host 0.0.0.0 --port 8000 &
    SERVER_PID=$!

    # Wait for server to be ready
    log_info "Waiting for server to become ready..."
    for i in $(seq 1 60); do
        if curl -s -o /dev/null -w "%{http_code}" http://localhost:8000/health | grep -q "200"; then
            log_info "✅ Server is ready!"
            break
        fi
        sleep 1
    done

    if ! curl -s -o /dev/null -w "%{http_code}" http://localhost:8000/health | grep -q "200"; then
        log_error "Server failed to start within 60 seconds"
        exit 1
    fi
}

# ============================================================================
# Step 5: Post-Deployment Validation
# ============================================================================
validate_deployment() {
    log_info "Running post-deployment validation..."

    local FAILURES=0

    # 1. Health check
    log_info "1/5 Checking health endpoint..."
    local HEALTH_CODE=$(curl -s -o /dev/null -w "%{http_code}" http://localhost:8000/health || true)
    if [ "$HEALTH_CODE" = "200" ]; then
        log_info "   ✅ Health check passed (HTTP 200)"
    else
        log_error "   ✗ Health check failed (HTTP $HEALTH_CODE)"
        FAILURES=$((FAILURES + 1))
    fi

    # 2. Model availability
    log_info "2/5 Checking model availability..."
    local MODEL_COUNT=$(ollama list 2>/dev/null | grep -c "$MODEL_NAME" || true)
    if [ "$MODEL_COUNT" -ge 1 ]; then
        log_info "   ✅ Model $MODEL_NAME is available ($(ollama list | grep "$MODEL_NAME" | awk '{print $1}'))"
    else
        log_error "   ✗ Model $MODEL_NAME not found"
        FAILURES=$((FAILURES + 1))
    fi

    # 3. API key validation
    log_info "3/5 Checking API key configuration..."
    if [ -n "$AGENT_API_KEY" ] && [ "$AGENT_API_KEY" != "your-super-secret-key" ]; then
        log_info "   ✅ API key is configured"
    else
        log_error "   ✗ API key not set or using default"
        FAILURES=$((FAILURES + 1))
    fi

    # 4. Database connectivity
    log_info "4/5 Checking PostgreSQL connectivity..."
    if docker exec "$(docker compose ps -q postgres)" pg_isready -U postgres 2>/dev/null; then
        log_info "   ✅ PostgreSQL is responsive"
    else
        log_warn "   ⚠ PostgreSQL check - may still be starting"
    fi

    # 5. Redis connectivity
    log_info "5/5 Checking Redis connectivity..."
    if redis-cli ping 2>/dev/null | grep -q PONG; then
        log_info "   ✅ Redis is responsive"
    else
        log_warn "   ⚠ Redis check - may still be starting"
    fi

    # Summary
    log_info ""
    if [ "$FAILURES" -eq 0 ]; then
        log_info "🎉 All validation checks passed!"
        return 0
    else
        log_warn "⚠ $FAILURES validation check(s) had warnings (some may be timing-related)"
        log_info "The system may still be operational - check individual components"
        return 1
    fi
}

# ============================================================================
# Step 6: First Agent Test
# ============================================================================
test_first_agent() {
    log_info "Running first agent test..."

    local TEST_RESULT
    TEST_RESULT=$(curl -s -X POST "http://localhost:8000/agent/runs" \
        -H "Authorization: Bearer $AGENT_API_KEY" \
        -H "Content-Type: application/json" \
        -d '{"task":"list files in /workspace", "model": "auto"}' 2>&1)

    if echo "$TEST_RESULT" | grep -q "run_id"; then
        log_info "✅ First agent test passed - run created successfully"
        log_info "   Run ID: $(echo "$TEST_RESULT" | grep -o 'run_id[^,]*' | head -1)"
        return 0
    else
        log_warn "⚠ First agent test completed (system may need warm-up time)"
        log_info "   Response: $(echo "$TEST_RESULT" | head -c 100)"
        return 1
    fi
}

# ============================================================================
# Main Execution
# ============================================================================
main() {
    log_info "=========================================="
    log_info "  AI Stack Deployment Script"
    log_info "  Target: 3 CPU cores / 12GB RAM"
    log_info "=========================================="
    echo ""

    # Execute all steps in sequence
    verify_resources
    echo ""
    configure_environment
    echo ""
    start_infrastructure
    echo ""
    start_server
    echo ""
    validate_deployment
    echo ""
    test_first_agent
    echo ""

    log_info "=========================================="
    log_info "  🚀 AI Stack Deployment Complete!"
    log_info "  Server running at: http://$(hostname -I | awk '{print $1}'):8000"
    log_info "  Health:            http://$(hostname -I | awk '{print $1}'):8000/health"
    log_info " =========================================="
}

# Run main function
main "$@"
