import { FormEvent, useEffect, useRef, useState } from "react";
import { api, Run, RunEvent, streamEvents } from "./api";

const terminal = new Set(["completed", "awaiting_approval", "failed", "discarded", "cancelled"]);
export function App() {
  const [key, setKey] = useState(""); const [task, setTask] = useState(""); const [workspace, setWorkspace] = useState("/workspace");
  const [model, setModel] = useState("coder"); const [models, setModels] = useState<string[]>(["coder"]); const [write, setWrite] = useState(false); const [runs, setRuns] = useState<Run[]>([]); const [active, setActive] = useState<Run | null>(null);
  const [events, setEvents] = useState<RunEvent[]>([]); const [answer, setAnswer] = useState(""); const [diff, setDiff] = useState(""); const [error, setError] = useState(""); const cursor = useRef(0);
  const loadRuns = async () => { if (!key) return; try { setRuns((await api<{runs: Run[]}>(key, "/runs")).runs); } catch (e) { setError(String(e)); } };
  useEffect(() => { void loadRuns(); }, [key]);
  useEffect(() => { if (!key) return; api<{models:string[]}>(key, "/models/available").then((data) => { setModels(data.models); if (!data.models.includes(model)) setModel(data.models[0] || "coder"); }).catch((e) => setError(String(e))); }, [key]);
  const consume = (event: RunEvent) => { setEvents((old) => [...old, event]); if (event.event_type === "output_delta") setAnswer((old) => old + String(event.payload.content || "")); if (event.event_type === "diff_ready") setDiff(String(event.payload.diff || "")); if (event.event_type === "run_completed" && !answer.endsWith("\n\n")) setAnswer((old) => `${old}\n\n`); if (event.event_type === "stream_closed") setActive((old) => old ? { ...old, status: event.status || old.status } : old); };
  const follow = async (run: Run) => { cursor.current = 0; setEvents([]); setAnswer(""); setDiff(""); setActive(run); try { while (!terminal.has(run.status)) { cursor.current = await streamEvents(key, run.id, cursor.current, consume); const current = await api<Run>(key, `/runs/${run.id}`); run = current; setActive(current); if (terminal.has(current.status)) break; } await loadRuns(); } catch (e) { setError(String(e)); } };
  const start = async (event: FormEvent) => { event.preventDefault(); setError(""); try { const result = await api<{run_id:string; status:string}>(key, "/runs", {method:"POST", body:JSON.stringify({task, workspace, model, allow_write:write})}); await follow({id:result.run_id,status:result.status,task,model,requested_workspace:workspace,allow_write:write,created_at:new Date().toISOString()}); } catch (e) { setError(String(e)); } };
  const action = async (name: "approve"|"discard"|"cancel") => { if (!active) return; try { await api(key, `/runs/${active.id}/${name}`, {method:"POST"}); await follow({...active,status:name === "cancel" ? "cancelling" : active.status}); } catch (e) { setError(String(e)); } };
  return <main><header><h1>AI Stack Runs</h1><p>Live, reviewable coding tasks.</p></header><section className="grid"><form onSubmit={start} className="card"><label>Agent API key<input type="password" value={key} onChange={(e)=>setKey(e.target.value)} /></label><label>Workspace<input value={workspace} onChange={(e)=>setWorkspace(e.target.value)} /></label><label>Model<select value={model} onChange={(e)=>setModel(e.target.value)}>{models.map((id)=><option key={id} value={id}>{id}</option>)}</select></label><label>Task<textarea value={task} onChange={(e)=>setTask(e.target.value)} required /></label><label className="check"><input type="checkbox" checked={write} onChange={(e)=>setWrite(e.target.checked)} /> Make changes in a reviewable Git sandbox</label><button disabled={!key}>Start run</button>{error && <pre className="error">{error}</pre>}</form><aside className="card"><h2>Recent runs</h2>{runs.map((run)=><button className="run" key={run.id} onClick={()=>void follow(run)}><b>{run.status} · {run.model}</b><span>{run.task}</span></button>)}</aside></section><section className="card"><h2>{active ? `Run ${active.id}` : "Activity"}</h2><div className="actions">{active && ["queued","running","cancelling"].includes(active.status) && <button onClick={()=>void action("cancel")}>Cancel</button>}{active?.status === "awaiting_approval" && <><button onClick={()=>void action("approve")}>Approve</button><button className="danger" onClick={()=>void action("discard")}>Discard</button></>}</div><pre className="answer">{answer || "Waiting for model output…"}</pre><div className="events">{events.map((event, i)=><div key={`${event.id || i}-${event.event_type}`}><b>{event.event_type}</b> {JSON.stringify(event.payload)}</div>)}</div>{diff && <><h3>Review diff</h3><pre className="diff">{diff}</pre></>}</section></main>;
}
